import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" class="light">
      <body
        className={` dark:bg-[#0e1217] dark:text-[#9ea9c3] dark:border-[#1c1f26]`}
      >
        {children}
      </body>
    </html>
  );
}
