version: "3.8"

services:
  next-development:
    build:
      context: .
      dockerfile: ./dockerfiles/dev.Dockerfile
    image: next-development
    container_name: next-app
    volumes:
      - $APP_VOLUMES_SRC:/app
      - ../src/node_modules:/app/node_modules
    ports:
      - $PORT:3000
    command: npm run dev